name: Waka Readme

on:
  push:
    branches:
      - "*"        # runs on all branches
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime stats
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update README with WakaTime
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
